// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umbkmykhuatbpzckcchq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtYmtteWtodWF0YnB6Y2tjY2hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTQzNDYsImV4cCI6MjA3MTYzMDM0Nn0.ZOKzRhU-hTgCYNhYXE9Spz_E0E-_ZGiDEu5MWbHhibE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});